version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:21-bullseye
    volumes:
      - ..:/workspaces:cached
    network_mode: service:db
    user: vscode
    command: sleep infinity

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: study_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: